/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesAnalyticsResponse } from './ResponsesAnalyticsResponse';
import {
  ResponsesAnalyticsResponseFromJSON,
  ResponsesAnalyticsResponseFromJSONTyped,
  ResponsesAnalyticsResponseToJSON,
  ResponsesAnalyticsResponseToJSONTyped,
} from './ResponsesAnalyticsResponse';

/**
 *
 * @export
 * @interface AnalyticsGet200Response
 */
export interface AnalyticsGet200Response {
  /**
   *
   * @type {ResponsesAnalyticsResponse}
   * @memberof AnalyticsGet200Response
   */
  data?: ResponsesAnalyticsResponse;
  /**
   *
   * @type {string}
   * @memberof AnalyticsGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the AnalyticsGet200Response interface.
 */
export function instanceOfAnalyticsGet200Response(
  value: object
): value is AnalyticsGet200Response {
  return true;
}

export function AnalyticsGet200ResponseFromJSON(
  json: any
): AnalyticsGet200Response {
  return AnalyticsGet200ResponseFromJSONTyped(json, false);
}

export function AnalyticsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesAnalyticsResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function AnalyticsGet200ResponseToJSON(
  json: any
): AnalyticsGet200Response {
  return AnalyticsGet200ResponseToJSONTyped(json, false);
}

export function AnalyticsGet200ResponseToJSONTyped(
  value?: AnalyticsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesAnalyticsResponseToJSON(value['data']),
    message: value['message'],
  };
}
