/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLoginResponse } from './ResponsesLoginResponse';
import {
  ResponsesLoginResponseFromJSON,
  ResponsesLoginResponseFromJSONTyped,
  ResponsesLoginResponseToJSON,
  ResponsesLoginResponseToJSONTyped,
} from './ResponsesLoginResponse';

/**
 *
 * @export
 * @interface AuthGoogleGet200Response
 */
export interface AuthGoogleGet200Response {
  /**
   *
   * @type {ResponsesLoginResponse}
   * @memberof AuthGoogleGet200Response
   */
  data?: ResponsesLoginResponse;
  /**
   *
   * @type {string}
   * @memberof AuthGoogleGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the AuthGoogleGet200Response interface.
 */
export function instanceOfAuthGoogleGet200Response(
  value: object
): value is AuthGoogleGet200Response {
  return true;
}

export function AuthGoogleGet200ResponseFromJSON(
  json: any
): AuthGoogleGet200Response {
  return AuthGoogleGet200ResponseFromJSONTyped(json, false);
}

export function AuthGoogleGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthGoogleGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesLoginResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function AuthGoogleGet200ResponseToJSON(
  json: any
): AuthGoogleGet200Response {
  return AuthGoogleGet200ResponseToJSONTyped(json, false);
}

export function AuthGoogleGet200ResponseToJSONTyped(
  value?: AuthGoogleGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesLoginResponseToJSON(value['data']),
    message: value['message'],
  };
}
