/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserResponse } from './ResponsesUserResponse';
import {
  ResponsesUserResponseFromJSON,
  ResponsesUserResponseFromJSONTyped,
  ResponsesUserResponseToJSON,
  ResponsesUserResponseToJSONTyped,
} from './ResponsesUserResponse';

/**
 *
 * @export
 * @interface AuthMeGet200Response
 */
export interface AuthMeGet200Response {
  /**
   *
   * @type {ResponsesUserResponse}
   * @memberof AuthMeGet200Response
   */
  data?: ResponsesUserResponse;
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the AuthMeGet200Response interface.
 */
export function instanceOfAuthMeGet200Response(
  value: object
): value is AuthMeGet200Response {
  return true;
}

export function AuthMeGet200ResponseFromJSON(json: any): AuthMeGet200Response {
  return AuthMeGet200ResponseFromJSONTyped(json, false);
}

export function AuthMeGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthMeGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesUserResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function AuthMeGet200ResponseToJSON(json: any): AuthMeGet200Response {
  return AuthMeGet200ResponseToJSONTyped(json, false);
}

export function AuthMeGet200ResponseToJSONTyped(
  value?: AuthMeGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesUserResponseToJSON(value['data']),
    message: value['message'],
  };
}
