/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLinkResponse } from './ResponsesLinkResponse';
import {
  ResponsesLinkResponseFromJSON,
  ResponsesLinkResponseFromJSONTyped,
  ResponsesLinkResponseToJSON,
  ResponsesLinkResponseToJSONTyped,
} from './ResponsesLinkResponse';

/**
 *
 * @export
 * @interface LinksIdGet200Response
 */
export interface LinksIdGet200Response {
  /**
   *
   * @type {ResponsesLinkResponse}
   * @memberof LinksIdGet200Response
   */
  data?: ResponsesLinkResponse;
  /**
   *
   * @type {string}
   * @memberof LinksIdGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the LinksIdGet200Response interface.
 */
export function instanceOfLinksIdGet200Response(
  value: object
): value is LinksIdGet200Response {
  return true;
}

export function LinksIdGet200ResponseFromJSON(
  json: any
): LinksIdGet200Response {
  return LinksIdGet200ResponseFromJSONTyped(json, false);
}

export function LinksIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LinksIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesLinkResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function LinksIdGet200ResponseToJSON(json: any): LinksIdGet200Response {
  return LinksIdGet200ResponseToJSONTyped(json, false);
}

export function LinksIdGet200ResponseToJSONTyped(
  value?: LinksIdGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesLinkResponseToJSON(value['data']),
    message: value['message'],
  };
}
