/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RequestsRegisterParam
 */
export interface RequestsRegisterParam {
  /**
   *
   * @type {string}
   * @memberof RequestsRegisterParam
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RequestsRegisterParam
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RequestsRegisterParam
   */
  password: string;
}

/**
 * Check if a given object implements the RequestsRegisterParam interface.
 */
export function instanceOfRequestsRegisterParam(
  value: object
): value is RequestsRegisterParam {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function RequestsRegisterParamFromJSON(
  json: any
): RequestsRegisterParam {
  return RequestsRegisterParamFromJSONTyped(json, false);
}

export function RequestsRegisterParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestsRegisterParam {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    name: json['name'],
    password: json['password'],
  };
}

export function RequestsRegisterParamToJSON(json: any): RequestsRegisterParam {
  return RequestsRegisterParamToJSONTyped(json, false);
}

export function RequestsRegisterParamToJSONTyped(
  value?: RequestsRegisterParam | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    name: value['name'],
    password: value['password'],
  };
}
