/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RequestsLoginParam
 */
export interface RequestsLoginParam {
  /**
   *
   * @type {string}
   * @memberof RequestsLoginParam
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RequestsLoginParam
   */
  password: string;
}

/**
 * Check if a given object implements the RequestsLoginParam interface.
 */
export function instanceOfRequestsLoginParam(
  value: object
): value is RequestsLoginParam {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function RequestsLoginParamFromJSON(json: any): RequestsLoginParam {
  return RequestsLoginParamFromJSONTyped(json, false);
}

export function RequestsLoginParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestsLoginParam {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function RequestsLoginParamToJSON(json: any): RequestsLoginParam {
  return RequestsLoginParamToJSONTyped(json, false);
}

export function RequestsLoginParamToJSONTyped(
  value?: RequestsLoginParam | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
  };
}
