/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RequestsInsertLinkParam
 */
export interface RequestsInsertLinkParam {
  /**
   *
   * @type {string}
   * @memberof RequestsInsertLinkParam
   */
  customShortCode?: string;
  /**
   *
   * @type {string}
   * @memberof RequestsInsertLinkParam
   */
  expiredAt?: string;
  /**
   *
   * @type {string}
   * @memberof RequestsInsertLinkParam
   */
  originalUrl: string;
}

/**
 * Check if a given object implements the RequestsInsertLinkParam interface.
 */
export function instanceOfRequestsInsertLinkParam(
  value: object
): value is RequestsInsertLinkParam {
  if (!('originalUrl' in value) || value['originalUrl'] === undefined)
    return false;
  return true;
}

export function RequestsInsertLinkParamFromJSON(
  json: any
): RequestsInsertLinkParam {
  return RequestsInsertLinkParamFromJSONTyped(json, false);
}

export function RequestsInsertLinkParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestsInsertLinkParam {
  if (json == null) {
    return json;
  }
  return {
    customShortCode:
      json['custom_short_code'] == null ? undefined : json['custom_short_code'],
    expiredAt: json['expired_at'] == null ? undefined : json['expired_at'],
    originalUrl: json['original_url'],
  };
}

export function RequestsInsertLinkParamToJSON(
  json: any
): RequestsInsertLinkParam {
  return RequestsInsertLinkParamToJSONTyped(json, false);
}

export function RequestsInsertLinkParamToJSONTyped(
  value?: RequestsInsertLinkParam | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    custom_short_code: value['customShortCode'],
    expired_at: value['expiredAt'],
    original_url: value['originalUrl'],
  };
}
