/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RequestsRefreshParam
 */
export interface RequestsRefreshParam {
  /**
   *
   * @type {string}
   * @memberof RequestsRefreshParam
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the RequestsRefreshParam interface.
 */
export function instanceOfRequestsRefreshParam(
  value: object
): value is RequestsRefreshParam {
  if (!('refreshToken' in value) || value['refreshToken'] === undefined)
    return false;
  return true;
}

export function RequestsRefreshParamFromJSON(json: any): RequestsRefreshParam {
  return RequestsRefreshParamFromJSONTyped(json, false);
}

export function RequestsRefreshParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestsRefreshParam {
  if (json == null) {
    return json;
  }
  return {
    refreshToken: json['refresh_token'],
  };
}

export function RequestsRefreshParamToJSON(json: any): RequestsRefreshParam {
  return RequestsRefreshParamToJSONTyped(json, false);
}

export function RequestsRefreshParamToJSONTyped(
  value?: RequestsRefreshParam | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    refresh_token: value['refreshToken'],
  };
}
