/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesLandingStatsResponse
 */
export interface ResponsesLandingStatsResponse {
  /**
   *
   * @type {number}
   * @memberof ResponsesLandingStatsResponse
   */
  totalActiveUsers?: number;
  /**
   *
   * @type {number}
   * @memberof ResponsesLandingStatsResponse
   */
  totalClicks?: number;
  /**
   *
   * @type {number}
   * @memberof ResponsesLandingStatsResponse
   */
  totalLinks?: number;
}

/**
 * Check if a given object implements the ResponsesLandingStatsResponse interface.
 */
export function instanceOfResponsesLandingStatsResponse(
  value: object
): value is ResponsesLandingStatsResponse {
  return true;
}

export function ResponsesLandingStatsResponseFromJSON(
  json: any
): ResponsesLandingStatsResponse {
  return ResponsesLandingStatsResponseFromJSONTyped(json, false);
}

export function ResponsesLandingStatsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesLandingStatsResponse {
  if (json == null) {
    return json;
  }
  return {
    totalActiveUsers:
      json['total_active_users'] == null
        ? undefined
        : json['total_active_users'],
    totalClicks:
      json['total_clicks'] == null ? undefined : json['total_clicks'],
    totalLinks: json['total_links'] == null ? undefined : json['total_links'],
  };
}

export function ResponsesLandingStatsResponseToJSON(
  json: any
): ResponsesLandingStatsResponse {
  return ResponsesLandingStatsResponseToJSONTyped(json, false);
}

export function ResponsesLandingStatsResponseToJSONTyped(
  value?: ResponsesLandingStatsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    total_active_users: value['totalActiveUsers'],
    total_clicks: value['totalClicks'],
    total_links: value['totalLinks'],
  };
}
