/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesBaseResponse
 */
export interface ResponsesBaseResponse {
  /**
   *
   * @type {object}
   * @memberof ResponsesBaseResponse
   */
  data?: object;
  /**
   *
   * @type {string}
   * @memberof ResponsesBaseResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the ResponsesBaseResponse interface.
 */
export function instanceOfResponsesBaseResponse(
  value: object
): value is ResponsesBaseResponse {
  return true;
}

export function ResponsesBaseResponseFromJSON(
  json: any
): ResponsesBaseResponse {
  return ResponsesBaseResponseFromJSONTyped(json, false);
}

export function ResponsesBaseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesBaseResponse {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : json['data'],
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function ResponsesBaseResponseToJSON(json: any): ResponsesBaseResponse {
  return ResponsesBaseResponseToJSONTyped(json, false);
}

export function ResponsesBaseResponseToJSONTyped(
  value?: ResponsesBaseResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value['data'],
    message: value['message'],
  };
}
