/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesUserResponse
 */
export interface ResponsesUserResponse {
  /**
   *
   * @type {string}
   * @memberof ResponsesUserResponse
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesUserResponse
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesUserResponse
   */
  isActive?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesUserResponse
   */
  isVerified?: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesUserResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesUserResponse
   */
  profileImageUrl?: string;
}

/**
 * Check if a given object implements the ResponsesUserResponse interface.
 */
export function instanceOfResponsesUserResponse(
  value: object
): value is ResponsesUserResponse {
  return true;
}

export function ResponsesUserResponseFromJSON(
  json: any
): ResponsesUserResponse {
  return ResponsesUserResponseFromJSONTyped(json, false);
}

export function ResponsesUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesUserResponse {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'] == null ? undefined : json['email'],
    id: json['id'] == null ? undefined : json['id'],
    isActive: json['is_active'] == null ? undefined : json['is_active'],
    isVerified: json['is_verified'] == null ? undefined : json['is_verified'],
    name: json['name'] == null ? undefined : json['name'],
    profileImageUrl:
      json['profile_image_url'] == null ? undefined : json['profile_image_url'],
  };
}

export function ResponsesUserResponseToJSON(json: any): ResponsesUserResponse {
  return ResponsesUserResponseToJSONTyped(json, false);
}

export function ResponsesUserResponseToJSONTyped(
  value?: ResponsesUserResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    id: value['id'],
    is_active: value['isActive'],
    is_verified: value['isVerified'],
    name: value['name'],
    profile_image_url: value['profileImageUrl'],
  };
}
