/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesAnalyticOverview
 */
export interface ResponsesAnalyticOverview {
  /**
   *
   * @type {string}
   * @memberof ResponsesAnalyticOverview
   */
  date?: string;
  /**
   *
   * @type {number}
   * @memberof ResponsesAnalyticOverview
   */
  value?: number;
}

/**
 * Check if a given object implements the ResponsesAnalyticOverview interface.
 */
export function instanceOfResponsesAnalyticOverview(
  value: object
): value is ResponsesAnalyticOverview {
  return true;
}

export function ResponsesAnalyticOverviewFromJSON(
  json: any
): ResponsesAnalyticOverview {
  return ResponsesAnalyticOverviewFromJSONTyped(json, false);
}

export function ResponsesAnalyticOverviewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesAnalyticOverview {
  if (json == null) {
    return json;
  }
  return {
    date: json['date'] == null ? undefined : json['date'],
    value: json['value'] == null ? undefined : json['value'],
  };
}

export function ResponsesAnalyticOverviewToJSON(
  json: any
): ResponsesAnalyticOverview {
  return ResponsesAnalyticOverviewToJSONTyped(json, false);
}

export function ResponsesAnalyticOverviewToJSONTyped(
  value?: ResponsesAnalyticOverview | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    date: value['date'],
    value: value['value'],
  };
}
