/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesErrorResponse
 */
export interface ResponsesErrorResponse {
  /**
   *
   * @type {object}
   * @memberof ResponsesErrorResponse
   */
  error?: object;
  /**
   *
   * @type {string}
   * @memberof ResponsesErrorResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the ResponsesErrorResponse interface.
 */
export function instanceOfResponsesErrorResponse(
  value: object
): value is ResponsesErrorResponse {
  return true;
}

export function ResponsesErrorResponseFromJSON(
  json: any
): ResponsesErrorResponse {
  return ResponsesErrorResponseFromJSONTyped(json, false);
}

export function ResponsesErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function ResponsesErrorResponseToJSON(
  json: any
): ResponsesErrorResponse {
  return ResponsesErrorResponseToJSONTyped(json, false);
}

export function ResponsesErrorResponseToJSONTyped(
  value?: ResponsesErrorResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
    message: value['message'],
  };
}
