/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AuthLoginPost200Response,
  AuthMeGet200Response,
  RequestsLoginParam,
  RequestsRefreshParam,
  RequestsRegisterParam,
  RequestsUpdateProfileParam,
  ResponsesErrorResponse,
} from '../models/index';
import {
  AuthLoginPost200ResponseFromJSON,
  AuthLoginPost200ResponseToJSON,
  AuthMeGet200ResponseFromJSON,
  AuthMeGet200ResponseToJSON,
  RequestsLoginParamFromJSON,
  RequestsLoginParamToJSON,
  RequestsRefreshParamFromJSON,
  RequestsRefreshParamToJSON,
  RequestsRegisterParamFromJSON,
  RequestsRegisterParamToJSON,
  RequestsUpdateProfileParamFromJSON,
  RequestsUpdateProfileParamToJSON,
  ResponsesErrorResponseFromJSON,
  ResponsesErrorResponseToJSON,
} from '../models/index';

export interface AuthLoginPostRequest {
  request: RequestsLoginParam;
}

export interface AuthRefreshPostRequest {
  request: RequestsRefreshParam;
}

export interface AuthRegisterPostRequest {
  request: RequestsRegisterParam;
}

export interface AuthUpdateProfilePutRequest {
  request: RequestsUpdateProfileParam;
}

/**
 * AuthApi - interface
 *
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
  /**
   * Authenticate user with email and password
   * @summary User login
   * @param {RequestsLoginParam} request Login credentials
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApiInterface
   */
  authLoginPostRaw(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>>;

  /**
   * Authenticate user with email and password
   * User login
   */
  authLoginPost(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response>;

  /**
   * Get current authenticated user profile
   * @summary Get user profile
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApiInterface
   */
  authMeGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthMeGet200Response>>;

  /**
   * Get current authenticated user profile
   * Get user profile
   */
  authMeGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthMeGet200Response>;

  /**
   * Get new access token using refresh token
   * @summary Refresh token
   * @param {RequestsRefreshParam} request Refresh token
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApiInterface
   */
  authRefreshPostRaw(
    requestParameters: AuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>>;

  /**
   * Get new access token using refresh token
   * Refresh token
   */
  authRefreshPost(
    requestParameters: AuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response>;

  /**
   * Create a new user account
   * @summary Register new user
   * @param {RequestsRegisterParam} request Registration details
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApiInterface
   */
  authRegisterPostRaw(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>>;

  /**
   * Create a new user account
   * Register new user
   */
  authRegisterPost(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response>;

  /**
   * Update current authenticated user profile
   * @summary Update user profile
   * @param {RequestsUpdateProfileParam} request Profile update details
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApiInterface
   */
  authUpdateProfilePutRaw(
    requestParameters: AuthUpdateProfilePutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthMeGet200Response>>;

  /**
   * Update current authenticated user profile
   * Update user profile
   */
  authUpdateProfilePut(
    requestParameters: AuthUpdateProfilePutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthMeGet200Response>;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {
  /**
   * Authenticate user with email and password
   * User login
   */
  async authLoginPostRaw(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
    if (requestParameters['request'] == null) {
      throw new runtime.RequiredError(
        'request',
        'Required parameter "request" was null or undefined when calling authLoginPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/login`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RequestsLoginParamToJSON(requestParameters['request']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthLoginPost200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Authenticate user with email and password
   * User login
   */
  async authLoginPost(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response> {
    const response = await this.authLoginPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get current authenticated user profile
   * Get user profile
   */
  async authMeGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthMeGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/auth/me`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthMeGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get current authenticated user profile
   * Get user profile
   */
  async authMeGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthMeGet200Response> {
    const response = await this.authMeGetRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get new access token using refresh token
   * Refresh token
   */
  async authRefreshPostRaw(
    requestParameters: AuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
    if (requestParameters['request'] == null) {
      throw new runtime.RequiredError(
        'request',
        'Required parameter "request" was null or undefined when calling authRefreshPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/refresh`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RequestsRefreshParamToJSON(requestParameters['request']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthLoginPost200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get new access token using refresh token
   * Refresh token
   */
  async authRefreshPost(
    requestParameters: AuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response> {
    const response = await this.authRefreshPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Create a new user account
   * Register new user
   */
  async authRegisterPostRaw(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
    if (requestParameters['request'] == null) {
      throw new runtime.RequiredError(
        'request',
        'Required parameter "request" was null or undefined when calling authRegisterPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/register`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RequestsRegisterParamToJSON(requestParameters['request']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthLoginPost200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Create a new user account
   * Register new user
   */
  async authRegisterPost(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthLoginPost200Response> {
    const response = await this.authRegisterPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Update current authenticated user profile
   * Update user profile
   */
  async authUpdateProfilePutRaw(
    requestParameters: AuthUpdateProfilePutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthMeGet200Response>> {
    if (requestParameters['request'] == null) {
      throw new runtime.RequiredError(
        'request',
        'Required parameter "request" was null or undefined when calling authUpdateProfilePut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/auth/update-profile`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: RequestsUpdateProfileParamToJSON(requestParameters['request']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthMeGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Update current authenticated user profile
   * Update user profile
   */
  async authUpdateProfilePut(
    requestParameters: AuthUpdateProfilePutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthMeGet200Response> {
    const response = await this.authUpdateProfilePutRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
