/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  DashboardStatsGet200Response,
  ResponsesErrorResponse,
} from '../models/index';
import {
  DashboardStatsGet200ResponseFromJSON,
  DashboardStatsGet200ResponseToJSON,
  ResponsesErrorResponseFromJSON,
  ResponsesErrorResponseToJSON,
} from '../models/index';

/**
 * DashboardApi - interface
 *
 * @export
 * @interface DashboardApiInterface
 */
export interface DashboardApiInterface {
  /**
   * Get total links created, active users, and total clicks
   * @summary Get landing page statistics
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  dashboardStatsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DashboardStatsGet200Response>>;

  /**
   * Get total links created, active users, and total clicks
   * Get landing page statistics
   */
  dashboardStatsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DashboardStatsGet200Response>;
}

/**
 *
 */
export class DashboardApi
  extends runtime.BaseAPI
  implements DashboardApiInterface
{
  /**
   * Get total links created, active users, and total clicks
   * Get landing page statistics
   */
  async dashboardStatsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DashboardStatsGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/dashboard/stats`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DashboardStatsGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get total links created, active users, and total clicks
   * Get landing page statistics
   */
  async dashboardStatsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DashboardStatsGet200Response> {
    const response = await this.dashboardStatsGetRaw(initOverrides);
    return await response.value();
  }
}
