/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  LinksAllGet200Response,
  LinksIdGet200Response,
  RequestsInsertLinkParam,
  ResponsesErrorResponse,
} from '../models/index';
import {
  LinksAllGet200ResponseFromJSON,
  LinksAllGet200ResponseToJSON,
  LinksIdGet200ResponseFromJSON,
  LinksIdGet200ResponseToJSON,
  RequestsInsertLinkParamFromJSON,
  RequestsInsertLinkParamToJSON,
  ResponsesErrorResponseFromJSON,
  ResponsesErrorResponseToJSON,
} from '../models/index';

export interface LinksAllGetRequest {
  page?: number;
  limit?: number;
  orderBy?: LinksAllGetOrderByEnum;
}

export interface LinksCreatePostRequest {
  request: RequestsInsertLinkParam;
}

export interface LinksIdDeleteRequest {
  id: string;
}

export interface LinksIdGetRequest {
  id: string;
}

/**
 * LinksApi - interface
 *
 * @export
 * @interface LinksApiInterface
 */
export interface LinksApiInterface {
  /**
   * Get all links for the authenticated user with pagination
   * @summary Get all links
   * @param {number} [page] Page number
   * @param {number} [limit] Items per page
   * @param {'created_at' | 'counts'} [orderBy] Order by field
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LinksApiInterface
   */
  linksAllGetRaw(
    requestParameters: LinksAllGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksAllGet200Response>>;

  /**
   * Get all links for the authenticated user with pagination
   * Get all links
   */
  linksAllGet(
    requestParameters: LinksAllGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksAllGet200Response>;

  /**
   * Create a new shortened link
   * @summary Create new link
   * @param {RequestsInsertLinkParam} request Link details
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LinksApiInterface
   */
  linksCreatePostRaw(
    requestParameters: LinksCreatePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksIdGet200Response>>;

  /**
   * Create a new shortened link
   * Create new link
   */
  linksCreatePost(
    requestParameters: LinksCreatePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksIdGet200Response>;

  /**
   * Delete a shortened link by its ID
   * @summary Delete an existing link
   * @param {string} id Link ID (UUID)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LinksApiInterface
   */
  linksIdDeleteRaw(
    requestParameters: LinksIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete a shortened link by its ID
   * Delete an existing link
   */
  linksIdDelete(
    requestParameters: LinksIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   * Get a specific link by its ID
   * @summary Get link by ID
   * @param {string} id Link ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LinksApiInterface
   */
  linksIdGetRaw(
    requestParameters: LinksIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksIdGet200Response>>;

  /**
   * Get a specific link by its ID
   * Get link by ID
   */
  linksIdGet(
    requestParameters: LinksIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksIdGet200Response>;
}

/**
 *
 */
export class LinksApi extends runtime.BaseAPI implements LinksApiInterface {
  /**
   * Get all links for the authenticated user with pagination
   * Get all links
   */
  async linksAllGetRaw(
    requestParameters: LinksAllGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksAllGet200Response>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['orderBy'] != null) {
      queryParameters['orderBy'] = requestParameters['orderBy'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/links/all`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LinksAllGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get all links for the authenticated user with pagination
   * Get all links
   */
  async linksAllGet(
    requestParameters: LinksAllGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksAllGet200Response> {
    const response = await this.linksAllGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Create a new shortened link
   * Create new link
   */
  async linksCreatePostRaw(
    requestParameters: LinksCreatePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksIdGet200Response>> {
    if (requestParameters['request'] == null) {
      throw new runtime.RequiredError(
        'request',
        'Required parameter "request" was null or undefined when calling linksCreatePost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/links/create`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RequestsInsertLinkParamToJSON(requestParameters['request']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LinksIdGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Create a new shortened link
   * Create new link
   */
  async linksCreatePost(
    requestParameters: LinksCreatePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksIdGet200Response> {
    const response = await this.linksCreatePostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Delete a shortened link by its ID
   * Delete an existing link
   */
  async linksIdDeleteRaw(
    requestParameters: LinksIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling linksIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/links/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a shortened link by its ID
   * Delete an existing link
   */
  async linksIdDelete(
    requestParameters: LinksIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.linksIdDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Get a specific link by its ID
   * Get link by ID
   */
  async linksIdGetRaw(
    requestParameters: LinksIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LinksIdGet200Response>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling linksIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/links/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LinksIdGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get a specific link by its ID
   * Get link by ID
   */
  async linksIdGet(
    requestParameters: LinksIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LinksIdGet200Response> {
    const response = await this.linksIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const LinksAllGetOrderByEnum = {
  CreatedAt: 'created_at',
  Counts: 'counts',
} as const;
export type LinksAllGetOrderByEnum =
  (typeof LinksAllGetOrderByEnum)[keyof typeof LinksAllGetOrderByEnum];
