// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
FROM users 
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
FROM users
WHERE google_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
FROM users
WHERE verification_token = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByToken(ctx context.Context, verificationToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const linkGoogleToUser = `-- name: LinkGoogleToUser :one
UPDATE users SET google_id = $1, is_verified = true, verified_at = NOW(), profile_image_url = $2
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

type LinkGoogleToUserParams struct {
	GoogleID        sql.NullString
	ProfileImageUrl sql.NullString
	ID              uuid.UUID
}

func (q *Queries) LinkGoogleToUser(ctx context.Context, arg LinkGoogleToUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkGoogleToUser,
		arg.GoogleID,
		arg.ProfileImageUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(
    name,
    email,
    password_hash,
    verification_token
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

type InsertUserParams struct {
	Name              string
	Email             string
	PasswordHash      sql.NullString
	VerificationToken sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.VerificationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const insertUserWithGoogle = `-- name: InsertUserWithGoogle :one
INSERT INTO users(
    name,
    email,
    google_id,
    is_verified,
    profile_image_url
) VALUES (
    $1,
    $2,
    $3,
    TRUE,
    $4
)
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

type InsertUserWithGoogleParams struct {
	Name            string
	Email           string
	GoogleID        sql.NullString
	ProfileImageUrl sql.NullString
}

func (q *Queries) InsertUserWithGoogle(ctx context.Context, arg InsertUserWithGoogleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUserWithGoogle,
		arg.Name,
		arg.Email,
		arg.GoogleID,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
name = $1, email = $2, password_hash = $3, is_verified = $4, profile_image_url = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

type UpdateUserParams struct {
	Name            string
	Email           string
	PasswordHash    sql.NullString
	IsVerified      bool
	ProfileImageUrl sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
		arg.ProfileImageUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const updateVerificationToken = `-- name: UpdateVerificationToken :one
UPDATE users SET verification_token = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

type UpdateVerificationTokenParams struct {
	VerificationToken sql.NullString
	ID                uuid.UUID
}

func (q *Queries) UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateVerificationToken,
		arg.VerificationToken,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET is_verified = true, verified_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, email, password_hash, is_active, is_verified, created_at, updated_at, deleted_at, google_id, profile_image_url, verification_token, verified_at
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}
