/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesDashboardResponse } from './ResponsesDashboardResponse';
import {
  ResponsesDashboardResponseFromJSON,
  ResponsesDashboardResponseFromJSONTyped,
  ResponsesDashboardResponseToJSON,
  ResponsesDashboardResponseToJSONTyped,
} from './ResponsesDashboardResponse';

/**
 *
 * @export
 * @interface AnalyticsDashboardGet200Response
 */
export interface AnalyticsDashboardGet200Response {
  /**
   *
   * @type {ResponsesDashboardResponse}
   * @memberof AnalyticsDashboardGet200Response
   */
  data?: ResponsesDashboardResponse;
  /**
   *
   * @type {string}
   * @memberof AnalyticsDashboardGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the AnalyticsDashboardGet200Response interface.
 */
export function instanceOfAnalyticsDashboardGet200Response(
  value: object
): value is AnalyticsDashboardGet200Response {
  return true;
}

export function AnalyticsDashboardGet200ResponseFromJSON(
  json: any
): AnalyticsDashboardGet200Response {
  return AnalyticsDashboardGet200ResponseFromJSONTyped(json, false);
}

export function AnalyticsDashboardGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsDashboardGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesDashboardResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function AnalyticsDashboardGet200ResponseToJSON(
  json: any
): AnalyticsDashboardGet200Response {
  return AnalyticsDashboardGet200ResponseToJSONTyped(json, false);
}

export function AnalyticsDashboardGet200ResponseToJSONTyped(
  value?: AnalyticsDashboardGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesDashboardResponseToJSON(value['data']),
    message: value['message'],
  };
}
