/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLandingStatsResponse } from './ResponsesLandingStatsResponse';
import {
  ResponsesLandingStatsResponseFromJSON,
  ResponsesLandingStatsResponseFromJSONTyped,
  ResponsesLandingStatsResponseToJSON,
  ResponsesLandingStatsResponseToJSONTyped,
} from './ResponsesLandingStatsResponse';

/**
 *
 * @export
 * @interface DashboardStatsGet200Response
 */
export interface DashboardStatsGet200Response {
  /**
   *
   * @type {ResponsesLandingStatsResponse}
   * @memberof DashboardStatsGet200Response
   */
  data?: ResponsesLandingStatsResponse;
  /**
   *
   * @type {string}
   * @memberof DashboardStatsGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the DashboardStatsGet200Response interface.
 */
export function instanceOfDashboardStatsGet200Response(
  value: object
): value is DashboardStatsGet200Response {
  return true;
}

export function DashboardStatsGet200ResponseFromJSON(
  json: any
): DashboardStatsGet200Response {
  return DashboardStatsGet200ResponseFromJSONTyped(json, false);
}

export function DashboardStatsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DashboardStatsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ResponsesLandingStatsResponseFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function DashboardStatsGet200ResponseToJSON(
  json: any
): DashboardStatsGet200Response {
  return DashboardStatsGet200ResponseToJSONTyped(json, false);
}

export function DashboardStatsGet200ResponseToJSONTyped(
  value?: DashboardStatsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResponsesLandingStatsResponseToJSON(value['data']),
    message: value['message'],
  };
}
