/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLinkResponse } from './ResponsesLinkResponse';
import {
  ResponsesLinkResponseFromJSON,
  ResponsesLinkResponseFromJSONTyped,
  ResponsesLinkResponseToJSON,
  ResponsesLinkResponseToJSONTyped,
} from './ResponsesLinkResponse';

/**
 *
 * @export
 * @interface LinksAllGet200Response
 */
export interface LinksAllGet200Response {
  /**
   *
   * @type {Array<ResponsesLinkResponse>}
   * @memberof LinksAllGet200Response
   */
  data?: Array<ResponsesLinkResponse>;
  /**
   *
   * @type {string}
   * @memberof LinksAllGet200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the LinksAllGet200Response interface.
 */
export function instanceOfLinksAllGet200Response(
  value: object
): value is LinksAllGet200Response {
  return true;
}

export function LinksAllGet200ResponseFromJSON(
  json: any
): LinksAllGet200Response {
  return LinksAllGet200ResponseFromJSONTyped(json, false);
}

export function LinksAllGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LinksAllGet200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(ResponsesLinkResponseFromJSON),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function LinksAllGet200ResponseToJSON(
  json: any
): LinksAllGet200Response {
  return LinksAllGet200ResponseToJSONTyped(json, false);
}

export function LinksAllGet200ResponseToJSONTyped(
  value?: LinksAllGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(ResponsesLinkResponseToJSON),
    message: value['message'],
  };
}
