/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RequestsUpdateProfileParam
 */
export interface RequestsUpdateProfileParam {
  /**
   *
   * @type {string}
   * @memberof RequestsUpdateProfileParam
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof RequestsUpdateProfileParam
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof RequestsUpdateProfileParam
   */
  password?: string;
}

/**
 * Check if a given object implements the RequestsUpdateProfileParam interface.
 */
export function instanceOfRequestsUpdateProfileParam(
  value: object
): value is RequestsUpdateProfileParam {
  return true;
}

export function RequestsUpdateProfileParamFromJSON(
  json: any
): RequestsUpdateProfileParam {
  return RequestsUpdateProfileParamFromJSONTyped(json, false);
}

export function RequestsUpdateProfileParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestsUpdateProfileParam {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'] == null ? undefined : json['email'],
    name: json['name'] == null ? undefined : json['name'],
    password: json['password'] == null ? undefined : json['password'],
  };
}

export function RequestsUpdateProfileParamToJSON(
  json: any
): RequestsUpdateProfileParam {
  return RequestsUpdateProfileParamToJSONTyped(json, false);
}

export function RequestsUpdateProfileParamToJSONTyped(
  value?: RequestsUpdateProfileParam | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    name: value['name'],
    password: value['password'],
  };
}
