/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesLinkResponse
 */
export interface ResponsesLinkResponse {
  /**
   *
   * @type {number}
   * @memberof ResponsesLinkResponse
   */
  clickCount?: number;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  customShortCode?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  expiredAt?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  originalUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLinkResponse
   */
  shortCode?: string;
}

/**
 * Check if a given object implements the ResponsesLinkResponse interface.
 */
export function instanceOfResponsesLinkResponse(
  value: object
): value is ResponsesLinkResponse {
  return true;
}

export function ResponsesLinkResponseFromJSON(
  json: any
): ResponsesLinkResponse {
  return ResponsesLinkResponseFromJSONTyped(json, false);
}

export function ResponsesLinkResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesLinkResponse {
  if (json == null) {
    return json;
  }
  return {
    clickCount: json['click_count'] == null ? undefined : json['click_count'],
    createdAt: json['created_at'] == null ? undefined : json['created_at'],
    customShortCode:
      json['custom_short_code'] == null ? undefined : json['custom_short_code'],
    expiredAt: json['expired_at'] == null ? undefined : json['expired_at'],
    id: json['id'] == null ? undefined : json['id'],
    originalUrl:
      json['original_url'] == null ? undefined : json['original_url'],
    shortCode: json['short_code'] == null ? undefined : json['short_code'],
  };
}

export function ResponsesLinkResponseToJSON(json: any): ResponsesLinkResponse {
  return ResponsesLinkResponseToJSONTyped(json, false);
}

export function ResponsesLinkResponseToJSONTyped(
  value?: ResponsesLinkResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    click_count: value['clickCount'],
    created_at: value['createdAt'],
    custom_short_code: value['customShortCode'],
    expired_at: value['expiredAt'],
    id: value['id'],
    original_url: value['originalUrl'],
    short_code: value['shortCode'],
  };
}
