/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLinkResponse } from './ResponsesLinkResponse';
import {
  ResponsesLinkResponseFromJSON,
  ResponsesLinkResponseFromJSONTyped,
  ResponsesLinkResponseToJSON,
  ResponsesLinkResponseToJSONTyped,
} from './ResponsesLinkResponse';
import type { ResponsesAnalyticOverview } from './ResponsesAnalyticOverview';
import {
  ResponsesAnalyticOverviewFromJSON,
  ResponsesAnalyticOverviewFromJSONTyped,
  ResponsesAnalyticOverviewToJSON,
  ResponsesAnalyticOverviewToJSONTyped,
} from './ResponsesAnalyticOverview';
import type { ResponsesTopLink } from './ResponsesTopLink';
import {
  ResponsesTopLinkFromJSON,
  ResponsesTopLinkFromJSONTyped,
  ResponsesTopLinkToJSON,
  ResponsesTopLinkToJSONTyped,
} from './ResponsesTopLink';

/**
 *
 * @export
 * @interface ResponsesDashboardResponse
 */
export interface ResponsesDashboardResponse {
  /**
   *
   * @type {Array<ResponsesAnalyticOverview>}
   * @memberof ResponsesDashboardResponse
   */
  overviews?: Array<ResponsesAnalyticOverview>;
  /**
   *
   * @type {Array<ResponsesLinkResponse>}
   * @memberof ResponsesDashboardResponse
   */
  recents?: Array<ResponsesLinkResponse>;
  /**
   *
   * @type {ResponsesTopLink}
   * @memberof ResponsesDashboardResponse
   */
  topLink?: ResponsesTopLink;
  /**
   *
   * @type {number}
   * @memberof ResponsesDashboardResponse
   */
  totalActiveLinks?: number;
  /**
   *
   * @type {number}
   * @memberof ResponsesDashboardResponse
   */
  totalClicks?: number;
}

/**
 * Check if a given object implements the ResponsesDashboardResponse interface.
 */
export function instanceOfResponsesDashboardResponse(
  value: object
): value is ResponsesDashboardResponse {
  return true;
}

export function ResponsesDashboardResponseFromJSON(
  json: any
): ResponsesDashboardResponse {
  return ResponsesDashboardResponseFromJSONTyped(json, false);
}

export function ResponsesDashboardResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesDashboardResponse {
  if (json == null) {
    return json;
  }
  return {
    overviews:
      json['overviews'] == null
        ? undefined
        : (json['overviews'] as Array<any>).map(
            ResponsesAnalyticOverviewFromJSON
          ),
    recents:
      json['recents'] == null
        ? undefined
        : (json['recents'] as Array<any>).map(ResponsesLinkResponseFromJSON),
    topLink:
      json['top_link'] == null
        ? undefined
        : ResponsesTopLinkFromJSON(json['top_link']),
    totalActiveLinks:
      json['total_active_links'] == null
        ? undefined
        : json['total_active_links'],
    totalClicks:
      json['total_clicks'] == null ? undefined : json['total_clicks'],
  };
}

export function ResponsesDashboardResponseToJSON(
  json: any
): ResponsesDashboardResponse {
  return ResponsesDashboardResponseToJSONTyped(json, false);
}

export function ResponsesDashboardResponseToJSONTyped(
  value?: ResponsesDashboardResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    overviews:
      value['overviews'] == null
        ? undefined
        : (value['overviews'] as Array<any>).map(
            ResponsesAnalyticOverviewToJSON
          ),
    recents:
      value['recents'] == null
        ? undefined
        : (value['recents'] as Array<any>).map(ResponsesLinkResponseToJSON),
    top_link: ResponsesTopLinkToJSON(value['topLink']),
    total_active_links: value['totalActiveLinks'],
    total_clicks: value['totalClicks'],
  };
}
