/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesGoogleLoginResponse
 */
export interface ResponsesGoogleLoginResponse {
  /**
   *
   * @type {string}
   * @memberof ResponsesGoogleLoginResponse
   */
  authUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesGoogleLoginResponse
   */
  state?: string;
}

/**
 * Check if a given object implements the ResponsesGoogleLoginResponse interface.
 */
export function instanceOfResponsesGoogleLoginResponse(
  value: object
): value is ResponsesGoogleLoginResponse {
  return true;
}

export function ResponsesGoogleLoginResponseFromJSON(
  json: any
): ResponsesGoogleLoginResponse {
  return ResponsesGoogleLoginResponseFromJSONTyped(json, false);
}

export function ResponsesGoogleLoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesGoogleLoginResponse {
  if (json == null) {
    return json;
  }
  return {
    authUrl: json['auth_url'] == null ? undefined : json['auth_url'],
    state: json['state'] == null ? undefined : json['state'],
  };
}

export function ResponsesGoogleLoginResponseToJSON(
  json: any
): ResponsesGoogleLoginResponse {
  return ResponsesGoogleLoginResponseToJSONTyped(json, false);
}

export function ResponsesGoogleLoginResponseToJSONTyped(
  value?: ResponsesGoogleLoginResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    auth_url: value['authUrl'],
    state: value['state'],
  };
}
