/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesLinkResponse } from './ResponsesLinkResponse';
import {
  ResponsesLinkResponseFromJSON,
  ResponsesLinkResponseFromJSONTyped,
  ResponsesLinkResponseToJSON,
  ResponsesLinkResponseToJSONTyped,
} from './ResponsesLinkResponse';

/**
 *
 * @export
 * @interface ResponsesTopLink
 */
export interface ResponsesTopLink {
  /**
   *
   * @type {ResponsesLinkResponse}
   * @memberof ResponsesTopLink
   */
  link?: ResponsesLinkResponse;
  /**
   *
   * @type {number}
   * @memberof ResponsesTopLink
   */
  totalClicks?: number;
}

/**
 * Check if a given object implements the ResponsesTopLink interface.
 */
export function instanceOfResponsesTopLink(
  value: object
): value is ResponsesTopLink {
  return true;
}

export function ResponsesTopLinkFromJSON(json: any): ResponsesTopLink {
  return ResponsesTopLinkFromJSONTyped(json, false);
}

export function ResponsesTopLinkFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesTopLink {
  if (json == null) {
    return json;
  }
  return {
    link:
      json['link'] == null
        ? undefined
        : ResponsesLinkResponseFromJSON(json['link']),
    totalClicks:
      json['total_clicks'] == null ? undefined : json['total_clicks'],
  };
}

export function ResponsesTopLinkToJSON(json: any): ResponsesTopLink {
  return ResponsesTopLinkToJSONTyped(json, false);
}

export function ResponsesTopLinkToJSONTyped(
  value?: ResponsesTopLink | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    link: ResponsesLinkResponseToJSON(value['link']),
    total_clicks: value['totalClicks'],
  };
}
