/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesTypeValue } from './ResponsesTypeValue';
import {
  ResponsesTypeValueFromJSON,
  ResponsesTypeValueFromJSONTyped,
  ResponsesTypeValueToJSON,
  ResponsesTypeValueToJSONTyped,
} from './ResponsesTypeValue';
import type { ResponsesAnalyticOverview } from './ResponsesAnalyticOverview';
import {
  ResponsesAnalyticOverviewFromJSON,
  ResponsesAnalyticOverviewFromJSONTyped,
  ResponsesAnalyticOverviewToJSON,
  ResponsesAnalyticOverviewToJSONTyped,
} from './ResponsesAnalyticOverview';
import type { ResponsesTopLink } from './ResponsesTopLink';
import {
  ResponsesTopLinkFromJSON,
  ResponsesTopLinkFromJSONTyped,
  ResponsesTopLinkToJSON,
  ResponsesTopLinkToJSONTyped,
} from './ResponsesTopLink';

/**
 *
 * @export
 * @interface ResponsesAnalyticsResponse
 */
export interface ResponsesAnalyticsResponse {
  /**
   *
   * @type {number}
   * @memberof ResponsesAnalyticsResponse
   */
  avgDailyClick?: number;
  /**
   *
   * @type {Array<ResponsesTypeValue>}
   * @memberof ResponsesAnalyticsResponse
   */
  browserUsages?: Array<ResponsesTypeValue>;
  /**
   *
   * @type {Array<ResponsesTypeValue>}
   * @memberof ResponsesAnalyticsResponse
   */
  deviceBreakdowns?: Array<ResponsesTypeValue>;
  /**
   *
   * @type {string}
   * @memberof ResponsesAnalyticsResponse
   */
  fromDate?: string;
  /**
   *
   * @type {Array<ResponsesAnalyticOverview>}
   * @memberof ResponsesAnalyticsResponse
   */
  overviews?: Array<ResponsesAnalyticOverview>;
  /**
   *
   * @type {string}
   * @memberof ResponsesAnalyticsResponse
   */
  timeRange?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesAnalyticsResponse
   */
  toDate?: string;
  /**
   *
   * @type {Array<ResponsesTypeValue>}
   * @memberof ResponsesAnalyticsResponse
   */
  topCountries?: Array<ResponsesTypeValue>;
  /**
   *
   * @type {ResponsesTopLink}
   * @memberof ResponsesAnalyticsResponse
   */
  topLink?: ResponsesTopLink;
  /**
   *
   * @type {number}
   * @memberof ResponsesAnalyticsResponse
   */
  totalActiveLinks?: number;
  /**
   *
   * @type {number}
   * @memberof ResponsesAnalyticsResponse
   */
  totalClicks?: number;
  /**
   *
   * @type {Array<ResponsesTypeValue>}
   * @memberof ResponsesAnalyticsResponse
   */
  trafficSources?: Array<ResponsesTypeValue>;
}

/**
 * Check if a given object implements the ResponsesAnalyticsResponse interface.
 */
export function instanceOfResponsesAnalyticsResponse(
  value: object
): value is ResponsesAnalyticsResponse {
  return true;
}

export function ResponsesAnalyticsResponseFromJSON(
  json: any
): ResponsesAnalyticsResponse {
  return ResponsesAnalyticsResponseFromJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesAnalyticsResponse {
  if (json == null) {
    return json;
  }
  return {
    avgDailyClick:
      json['avg_daily_click'] == null ? undefined : json['avg_daily_click'],
    browserUsages:
      json['browser_usages'] == null
        ? undefined
        : (json['browser_usages'] as Array<any>).map(
            ResponsesTypeValueFromJSON
          ),
    deviceBreakdowns:
      json['device_breakdowns'] == null
        ? undefined
        : (json['device_breakdowns'] as Array<any>).map(
            ResponsesTypeValueFromJSON
          ),
    fromDate: json['from_date'] == null ? undefined : json['from_date'],
    overviews:
      json['overviews'] == null
        ? undefined
        : (json['overviews'] as Array<any>).map(
            ResponsesAnalyticOverviewFromJSON
          ),
    timeRange: json['time_range'] == null ? undefined : json['time_range'],
    toDate: json['to_date'] == null ? undefined : json['to_date'],
    topCountries:
      json['top_countries'] == null
        ? undefined
        : (json['top_countries'] as Array<any>).map(ResponsesTypeValueFromJSON),
    topLink:
      json['top_link'] == null
        ? undefined
        : ResponsesTopLinkFromJSON(json['top_link']),
    totalActiveLinks:
      json['total_active_links'] == null
        ? undefined
        : json['total_active_links'],
    totalClicks:
      json['total_clicks'] == null ? undefined : json['total_clicks'],
    trafficSources:
      json['traffic_sources'] == null
        ? undefined
        : (json['traffic_sources'] as Array<any>).map(
            ResponsesTypeValueFromJSON
          ),
  };
}

export function ResponsesAnalyticsResponseToJSON(
  json: any
): ResponsesAnalyticsResponse {
  return ResponsesAnalyticsResponseToJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseToJSONTyped(
  value?: ResponsesAnalyticsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    avg_daily_click: value['avgDailyClick'],
    browser_usages:
      value['browserUsages'] == null
        ? undefined
        : (value['browserUsages'] as Array<any>).map(ResponsesTypeValueToJSON),
    device_breakdowns:
      value['deviceBreakdowns'] == null
        ? undefined
        : (value['deviceBreakdowns'] as Array<any>).map(
            ResponsesTypeValueToJSON
          ),
    from_date: value['fromDate'],
    overviews:
      value['overviews'] == null
        ? undefined
        : (value['overviews'] as Array<any>).map(
            ResponsesAnalyticOverviewToJSON
          ),
    time_range: value['timeRange'],
    to_date: value['toDate'],
    top_countries:
      value['topCountries'] == null
        ? undefined
        : (value['topCountries'] as Array<any>).map(ResponsesTypeValueToJSON),
    top_link: ResponsesTopLinkToJSON(value['topLink']),
    total_active_links: value['totalActiveLinks'],
    total_clicks: value['totalClicks'],
    traffic_sources:
      value['trafficSources'] == null
        ? undefined
        : (value['trafficSources'] as Array<any>).map(ResponsesTypeValueToJSON),
  };
}
