/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesTypeValue
 */
export interface ResponsesTypeValue {
  /**
   *
   * @type {string}
   * @memberof ResponsesTypeValue
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof ResponsesTypeValue
   */
  value?: number;
}

/**
 * Check if a given object implements the ResponsesTypeValue interface.
 */
export function instanceOfResponsesTypeValue(
  value: object
): value is ResponsesTypeValue {
  return true;
}

export function ResponsesTypeValueFromJSON(json: any): ResponsesTypeValue {
  return ResponsesTypeValueFromJSONTyped(json, false);
}

export function ResponsesTypeValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesTypeValue {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    value: json['value'] == null ? undefined : json['value'],
  };
}

export function ResponsesTypeValueToJSON(json: any): ResponsesTypeValue {
  return ResponsesTypeValueToJSONTyped(json, false);
}

export function ResponsesTypeValueToJSONTyped(
  value?: ResponsesTypeValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    value: value['value'],
  };
}
