/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserResponse } from './ResponsesUserResponse';
import {
  ResponsesUserResponseFromJSON,
  ResponsesUserResponseFromJSONTyped,
  ResponsesUserResponseToJSON,
  ResponsesUserResponseToJSONTyped,
} from './ResponsesUserResponse';

/**
 *
 * @export
 * @interface ResponsesLoginResponse
 */
export interface ResponsesLoginResponse {
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  authUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  refreshToken?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  refreshTokenExpiredAt?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  state?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  token?: string;
  /**
   *
   * @type {string}
   * @memberof ResponsesLoginResponse
   */
  tokenExpiredAt?: string;
  /**
   *
   * @type {ResponsesUserResponse}
   * @memberof ResponsesLoginResponse
   */
  user?: ResponsesUserResponse;
}

/**
 * Check if a given object implements the ResponsesLoginResponse interface.
 */
export function instanceOfResponsesLoginResponse(
  value: object
): value is ResponsesLoginResponse {
  return true;
}

export function ResponsesLoginResponseFromJSON(
  json: any
): ResponsesLoginResponse {
  return ResponsesLoginResponseFromJSONTyped(json, false);
}

export function ResponsesLoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResponsesLoginResponse {
  if (json == null) {
    return json;
  }
  return {
    authUrl: json['auth_url'] == null ? undefined : json['auth_url'],
    refreshToken:
      json['refresh_token'] == null ? undefined : json['refresh_token'],
    refreshTokenExpiredAt:
      json['refresh_token_expired_at'] == null
        ? undefined
        : json['refresh_token_expired_at'],
    state: json['state'] == null ? undefined : json['state'],
    token: json['token'] == null ? undefined : json['token'],
    tokenExpiredAt:
      json['token_expired_at'] == null ? undefined : json['token_expired_at'],
    user:
      json['user'] == null
        ? undefined
        : ResponsesUserResponseFromJSON(json['user']),
  };
}

export function ResponsesLoginResponseToJSON(
  json: any
): ResponsesLoginResponse {
  return ResponsesLoginResponseToJSONTyped(json, false);
}

export function ResponsesLoginResponseToJSONTyped(
  value?: ResponsesLoginResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    auth_url: value['authUrl'],
    refresh_token: value['refreshToken'],
    refresh_token_expired_at: value['refreshTokenExpiredAt'],
    state: value['state'],
    token: value['token'],
    token_expired_at: value['tokenExpiredAt'],
    user: ResponsesUserResponseToJSON(value['user']),
  };
}
