/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AnalyticsDashboardGet200Response,
  AnalyticsGet200Response,
  ResponsesErrorResponse,
} from '../models/index';
import {
  AnalyticsDashboardGet200ResponseFromJSON,
  AnalyticsDashboardGet200ResponseToJSON,
  AnalyticsGet200ResponseFromJSON,
  AnalyticsGet200ResponseToJSON,
  ResponsesErrorResponseFromJSON,
  ResponsesErrorResponseToJSON,
} from '../models/index';

export interface AnalyticsGetRequest {
  range?: AnalyticsGetRangeEnum;
}

/**
 * AnalyticsApi - interface
 *
 * @export
 * @interface AnalyticsApiInterface
 */
export interface AnalyticsApiInterface {
  /**
   * Get dashboard overview including total clicks, active links, top link, and recent links
   * @summary Get dashboard data
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AnalyticsApiInterface
   */
  analyticsDashboardGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AnalyticsDashboardGet200Response>>;

  /**
   * Get dashboard overview including total clicks, active links, top link, and recent links
   * Get dashboard data
   */
  analyticsDashboardGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AnalyticsDashboardGet200Response>;

  /**
   * Get detailed analytics including device breakdowns, countries, traffic sources, and browser usage
   * @summary Get analytics data
   * @param {'7d' | '30d' | '90d' | 'all'} [range] Time range
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AnalyticsApiInterface
   */
  analyticsGetRaw(
    requestParameters: AnalyticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AnalyticsGet200Response>>;

  /**
   * Get detailed analytics including device breakdowns, countries, traffic sources, and browser usage
   * Get analytics data
   */
  analyticsGet(
    requestParameters: AnalyticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AnalyticsGet200Response>;
}

/**
 *
 */
export class AnalyticsApi
  extends runtime.BaseAPI
  implements AnalyticsApiInterface
{
  /**
   * Get dashboard overview including total clicks, active links, top link, and recent links
   * Get dashboard data
   */
  async analyticsDashboardGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AnalyticsDashboardGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/analytics/dashboard`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnalyticsDashboardGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get dashboard overview including total clicks, active links, top link, and recent links
   * Get dashboard data
   */
  async analyticsDashboardGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AnalyticsDashboardGet200Response> {
    const response = await this.analyticsDashboardGetRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get detailed analytics including device breakdowns, countries, traffic sources, and browser usage
   * Get analytics data
   */
  async analyticsGetRaw(
    requestParameters: AnalyticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AnalyticsGet200Response>> {
    const queryParameters: any = {};

    if (requestParameters['range'] != null) {
      queryParameters['range'] = requestParameters['range'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        await this.configuration.apiKey('Authorization'); // BearerAuth authentication
    }

    let urlPath = `/analytics/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnalyticsGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get detailed analytics including device breakdowns, countries, traffic sources, and browser usage
   * Get analytics data
   */
  async analyticsGet(
    requestParameters: AnalyticsGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AnalyticsGet200Response> {
    const response = await this.analyticsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}

/**
 * @export
 */
export const AnalyticsGetRangeEnum = {
  _7d: '7d',
  _30d: '30d',
  _90d: '90d',
  All: 'all',
} as const;
export type AnalyticsGetRangeEnum =
  (typeof AnalyticsGetRangeEnum)[keyof typeof AnalyticsGetRangeEnum];
