/* tslint:disable */
/* eslint-disable */
/**
 * Pendek.in API
 * URL Shortener API with analytics and link management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pendek.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ResponsesErrorResponse } from '../models/index';
import {
  ResponsesErrorResponseFromJSON,
  ResponsesErrorResponseToJSON,
} from '../models/index';

export interface CodeGetRequest {
  code: string;
}

/**
 * RedirectApi - interface
 *
 * @export
 * @interface RedirectApiInterface
 */
export interface RedirectApiInterface {
  /**
   * Redirect to the original URL using the short code
   * @summary Redirect to original URL
   * @param {string} code Short code
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RedirectApiInterface
   */
  codeGetRaw(
    requestParameters: CodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Redirect to the original URL using the short code
   * Redirect to original URL
   */
  codeGet(
    requestParameters: CodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;
}

/**
 *
 */
export class RedirectApi
  extends runtime.BaseAPI
  implements RedirectApiInterface
{
  /**
   * Redirect to the original URL using the short code
   * Redirect to original URL
   */
  async codeGetRaw(
    requestParameters: CodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['code'] == null) {
      throw new runtime.RequiredError(
        'code',
        'Required parameter "code" was null or undefined when calling codeGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/{code}`;
    urlPath = urlPath.replace(
      `{${'code'}}`,
      encodeURIComponent(String(requestParameters['code']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Redirect to the original URL using the short code
   * Redirect to original URL
   */
  async codeGet(
    requestParameters: CodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.codeGetRaw(requestParameters, initOverrides);
  }
}
